### ISSUE TITLE
Adding 2 different databases on same host (remote)

### ISSUE THREAD

**Issue by seqizz** [powa-team/powa-collector#15]
(oops sorry I pressed enter too early, adding context :) )

While adding remote servers, I realized I can't add 2 different databases from same postgresql instance, because:

```
ERROR:  duplicate key value violates unique constraint "powa_servers_hostname_port_key"
DETAIL:  Key (hostname, port)=(mydbhost, 5432) already exists.
```

Is this expected? Since the dbname field is string, I am not sure what should be the separator (if supported).

**Comment by rjuju** [comment]
Hi,

Yes the unique constraints are meant to avoid that.  What would be the use case for adding multiple databases for the same remote server?  All the metrics are instance-wide, not specific to a database so you would get the same information on each database anyway.

**Comment by seqizz** [comment]
Thanks for fast response. 

I thought collector will get the information per database, since we're going to be registering the extensions per-db. But I guess `GRANT pg_read_all_stats` is what it needs if this is the case. I will re-check what I did, this was a nice info, thanks!

**Comment by rjuju** [comment]
To be more complete, powa-collector simply retrieves the data from some "stat extension" like pg_stat_statements.  Those extensions work on 2 level:
- the C module, configured in shared_preload_libraries, is hooked into the executor (or similar depending on the extension) and see all activity for all users on all databases and save some metadata in shared memory
- the SQL extension can be created on 0, 1 or more databases and simply look at what's stored in the C module's shared memory and display it.  The underlying function indeed check some privileges (although for pg_stat_statements it's about seeing possibly sensitive data like the query text, you always see all the rows)

So for powa you simply need one database where all the necessary sql extensions are created to fetch the various datasources you need.  It's usually better to create a dedicated database, so for instance you can prevent the role used to connect from other databases and things like that.  If you need access to pg_stat_statements or other extensions for other needs, nothing prevents you from creating the extension in other databases for instance.
